name: deploy 
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: setup git auth
        env:
          email: 'rinaciodacosta@gmail.com'
          username: 'RafaelLeone'
        run: |
          git config --global user.email $email
          git config --global user.name $username
      - run: |
          npm i
          NODE_ENV=production npm run build
          cd dist
          git init
          git add .
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git push -f "git@github.com:RafaelLeone/game_of_life.git" main:gh-pages
